import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <nav>
          <ul className={"flex gap-5"}>
            <li><a href={"/"}>HOME</a></li>
            <li><a href={"/hiragana-table"}>hiragana table</a></li>
            <li><a href={"/roman-to-japanese"}>roman to japanese</a></li>
            <li><a href={"/syllabary"}>THEME</a></li>
            <li><a href={"/syllabary"}>TRANSLATE</a></li>
            <li><a href={"/syllabary"}>VOCABULARY</a></li>
            <li><a href={"/syllabary"}>DICTIONARY</a></li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
