INSERT INTO public.word
(roman, hiragana, katakana)
VALUES
    ('cheerful', 'あかるい', null),
    ('sir', 'さん', null),
    ('miss', 'さん', null),
    ('person', 'ひと', null),
    ('cool', 'かっこいい', null),
    ('funny', 'おもしろい', null),
    ('bus stop', 'バスてい', null),
    ('here', 'ここ', null),
    ('where', 'どこ', null),
    ('this', 'これ', null),
    ('department store', null, 'デパート'),
    ('naomi', 'なおみ', null),
    ('america', null, 'アメリカ'),
    ('big', 'おおきい', null),
    ('canada', null, 'カナダ'),
    ('brazil', null, 'ブラジル'),
    ('england', null, 'イギリス'),
    ('curry', null, 'カレー'),
    ('that', 'それ', null),
    ('tasty', 'おいしい', null),
    ('hello', 'こんにちは', null),
    ('good evening', 'こんばんは', null),
    ('bye', 'じゃあね', null),
    ('see you tomorrow', 'またあした', null),
    ('doctor', 'いしゃ', null),
    ('teacher', 'せんせい', null),
    ('lawyer', 'べんごし', null),
    ('nice', 'やさしい', null),
    ('sushi', 'すし', null),
    ('please', 'ください', null),
    ('green tea', 'おちゃ', null),
    ('riz', 'ごはん', null),
    ('and', 'と', null),
    ('water', 'みず', null),
    ('hana', 'はな', null),
    ('nice to meet you', 'どうぞよろしく', null),
    ('ken', 'けん', null),
    ('my', 'わたしの', null),
    ('hat', 'ぼうし', null),
    ('umbrella', 'かさ', null),
    ('red', 'あかい', null),
    ('shoe', 'くつ', null),
    ('coat', null, 'コート'),
    ('tanaka', 'たなか', null),
    ('nakayama', 'なかやま', null),
    ('these', 'これら', null),
    ('yamaguchi', 'やまぐち', null),
    ('excuse me', 'すみません', null),
    ('it is', 'です', null),
    ('it is not', 'じゃないです', null),
    ('one', 'いち', null),
    ('two', 'に', null),
    ('three', 'さん', null),
    ('four', 'よん', null),
    ('cute', 'やさい', null),
    ('yes', 'はい', null),
    ('no', 'いいえ', null);
