export const vocabularyRecord: Record<string, string> = {
    "cheerful": "あかるい",
    "sir": "さん",
    "miss": "さん",
    "person": "ひと",
    "cool": "かっこいい",
    "funny": "おもしろい",
    "bus stop": "バスてい",
    "here": "ここ",
    "where": "どこ",
    "this": "これ",
    "department store": "デパート",
    "naomi": "なおみ",
    "america": "アメリカ",
    "american": "アメリカじん",
    "big": "おおきい",
    "canada": "カナダ",
    "canadian": "カナダじん",
    "brazil": "ブラジル",
    "brazilian": "ブラジルじん",
    "england": "イギリス",
    "english": "イギリスじん",
    "curry": "カレー",
    "that": "それ",
    "tasty": "おいしい",
    "hello": "こんにちは",
    "good evening": "こんばんは",
    "bye": "じゃあね",
    "see you tomorrow": "またあした",
    "doctor": "いしゃ",
    "teacher": "せんせい",
    "lawyer": "べんごし",
    "nice": "やさしい",
    "sushi": "すし",
    "please": "ください",
    "green tea": "おちゃ",
    "riz": "ごはん",
    "and": "と",
    "water": "みず",
    "hana": "はな",
    "nice to meet you": "どうぞよろしく",
    "ken": "けん",
    "my": "わたしの",
    "hat": "ぼうし",
    "umbrella": "かさ",
    "red": "あかい",
    "shoe": "くつ",
    "coat": "コート",
    "tanaka": "たなか",
    "nakayama": "なかやま",
    "these": "これら",
    "yamaguchi": "やまぐち",
    "excuse me": "すみません",
    "it is": "です",
    "it is not": "じゃないです",
    "one": "いち",
    "two": "に",
    "three": "さん",
    "four": "よん",
}
